/*
   -- Antasena --
   
   To compile this code using RemoteXY library 3.1.13 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.15.01 or later version;
     - for iOS 1.12.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.    
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLUETOOTH

#include <BluetoothSerial.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "Antasena"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 111 bytes
  { 255,6,0,4,0,104,0,19,0,0,0,65,110,116,97,115,101,110,97,0,
  179,2,106,200,200,80,1,1,5,0,5,205,48,150,150,8,36,41,41,32,
  2,26,1,5,27,35,150,150,150,37,41,41,32,2,26,31,1,22,23,60,
  60,33,5,19,19,0,2,31,80,101,108,111,110,116,97,114,0,1,52,20,
  60,60,7,5,19,19,0,2,31,72,105,100,114,111,108,105,107,0,67,4,
  15,21,25,86,5,28,11,109,2,26,2 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_x; // from -100 to 100
  int8_t joystick_y; // from -100 to 100
  int8_t joystick_z; // from -100 to 100
  int8_t joystick_a; // from -100 to 100
  uint8_t button_pelontar; // =1 if button pressed, else =0
  uint8_t button_relay; // =1 if button pressed, else =0

    // output variables
  float kecepatan;

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

void setup() 
{
  RemoteXY_Init(); 
  Serial.begin(115200);  // Mulai Serial Monitor
  
  Serial.println("Antasena siap tempur! 🚀");
}

void loop() 
{ 
  RemoteXY_Handler();
  
  // Baca nilai joystick
  int x = RemoteXY.joystick_x;
  int y = RemoteXY.joystick_y;
  int z = RemoteXY.joystick_z;
  int a = RemoteXY.joystick_a;

  // Baca tombol
  int tombolPelontar = RemoteXY.button_pelontar;
  int tombolRelay = RemoteXY.button_relay;

  Serial.print("x : ");
  Serial.println(x);
  Serial.print("y : ");
  Serial.println(y);
  Serial.print("z : ");
  Serial.println(z);
  Serial.print("Pelontar : ");
  Serial.println(tombolPelontar);
  Serial.print("Hidrolik : ");
  Serial.println(tombolRelay);
  Serial.println("================================================");

  // Tambahkan delay agar gak spam
  RemoteXY_delay(200);
}
